name: Render, Build, and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Restore extracted data from cache
        id: restore-cache
        uses: actions/cache@v4
        with:
          path: public/maps
          key: v1 # TODO: use submodule hash

      - if: ${{ steps.restore-cache.outputs.cache-hit != 'true' }}
        name: Setup Submodule
        run: |
          git submodule update --init --recursive

      - if: ${{ steps.restore-cache.outputs.cache-hit != 'true' }}
        name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - if: ${{ steps.restore-cache.outputs.cache-hit != 'true' }}
        name: Restore dependencies
        run: dotnet restore

      - if: ${{ steps.restore-cache.outputs.cache-hit != 'true' }}
        name: Apply map renderer patch
        run: git -C ss14-sunrise apply patches/update-map-renderer.patch
      
      - if: ${{ steps.restore-cache.outputs.cache-hit != 'true' }}
        name: Build map renderer
        run: dotnet build ss14-sunrise/Content.MapRenderer --configuration Release --no-restore

      - if: ${{ steps.restore-cache.outputs.cache-hit != 'true' }}
        name: Render maps
        run: dotnet run --project ss14-sunrise/Content.MapRenderer --no-restore -- --viewer Dev SunriseBox

      - if: ${{ steps.restore-cache.outputs.cache-hit != 'true' }}
        name: Write map list file
        run: |
          echo '{"maps": [
            { "id": "Dev", "name": "Dev"},
            { "id": "SunriseBox", "name": "Box" }
          ]}' > public/list.json

      - if: ${{ steps.restore-cache.outputs.cache-hit != 'true' }}
        name: Move rendered maps
        run: mv ss14-sunrise/Resources/MapImages/* public/maps/

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build

      - name: Upload files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
